# Generated by Django 2.1.5 on 2019-02-14 06:19

import dice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='document',
            field=models.ImageField(upload_to=dice.models.user_directory_path),
        ),
    ]
