# Generated by Django 2.1.5 on 2019-02-14 06:43

import dice.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dice', '0002_auto_20190214_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='image_height',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upload',
            name='image_width',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='upload',
            name='document',
            field=models.ImageField(height_field='image_height', upload_to=dice.models.user_directory_path, width_field='image_width'),
        ),
    ]
