# Generated by Django 2.1.5 on 2019-02-20 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dice', '0004_auto_20190217_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='document',
            new_name='file',
        ),
    ]
