# Generated by Django 2.1.5 on 2019-02-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dice', '0006_upload_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiceTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dice_size', models.IntegerField()),
                ('dice_cost', models.IntegerField()),
            ],
        ),
    ]
