# Generated by Django 2.1.5 on 2019-03-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dice', '0007_dicetypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_per_dice', models.IntegerField()),
            ],
        ),
    ]
