# Generated by Django 2.1.5 on 2020-02-08 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dice', '0010_diceimage_uploaded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diceimage',
            name='uploaded_by',
        ),
    ]
