# Generated by Django 2.1.5 on 2020-02-08 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dice', '0013_auto_20200208_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='diceimage',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 27, 17, 37, 47, 428253)),
        ),
    ]
